test:
  demo:
    property1: "Value from application.yml"
    encrypted: "{cipher}43bf410c2e0c0056edb8f270792d187cf6b4233e90faf29f6a72c644379e4d4590bbece8eafbd6247f198c45840b6125"

logging:
  level:
    root: INFO
    dev.dead: INFO
management.zipkin.tracing.endpoint: http://zipkin-server:9411/api/v2/spans
management.tracing.sampling.probability: 1.0
