spring:
  application:
    name: service-c

management:
  tracing:
    sampling:
      probability: 1.0  # Send 100% of traces to Zipkin (default is 0.1)
    # Spring Boot 4.0: Zipkin config moved under tracing.export.zipkin
    export:
      zipkin:
        endpoint: "http://localhost:9411/api/v2/spans"
        enabled: true

# Include traceId and spanId in log output (from MDC populated by Micrometer Tracing)
logging:
  pattern:
    level: "%5p [${spring.application.name:-},%X{traceId:-},%X{spanId:-}]"
